export const PRODUCT_LIST_REQUEST = 'PRODUCT_LIST_REQUEST ';
export const PRODUCT_LIST_SUCCESS = 'PRODUCT_LIST_SUCCESS ';
export const PRODUCT_LIST_FAIL = 'PRODUCT_LIST_FAIL ';

export const PRODUCT_DETAILS_REQUEST = 'DETAILS_LIST_REQUEST ';
export const PRODUCT_DETAILS_SUCCESS = 'DETAILS_LIST_SUCCESS ';
export const PRODUCT_DETAILS_FAIL = 'DETAILS_LIST_FAIL ';

export const PRODUCT_SAVE_REQUEST = 'DETAILS_SAVE_REQUEST ';
export const PRODUCT_SAVE_SUCCESS = 'DETAILS_SAVE_SUCCESS ';
export const PRODUCT_SAVE_FAIL = 'DETAILS_SAVE_FAIL ';

export const PRODUCT_DELETE_REQUEST = 'DETAILS_SAVE_REQUEST ';
export const PRODUCT_DELETE_SUCCESS = 'DETAILS_SAVE_SUCCESS ';
export const PRODUCT_DELETE_FAIL = 'DETAILS_SAVE_FAIL ';
